name: build-rust-windows-dispatch

on:
  workflow_dispatch

jobs:
  get_release:
    # https://github.com/octokit/request-action
    name: Get release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.get_upload_url.outputs.url }}
    steps:
    - uses: octokit/request-action@v2.x
      id: get_latest_release
      with:
        route: GET /repos/{owner}/{repo}/releases/latest
        owner: esp-rs
        repo: rust-build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: get upload url
      id: get_upload_url
      run: |
        url=$(echo "$response" | jq -r '.upload_url')
        echo "::set-output name=url::$url"
      env:
        response:  ${{ steps.get_latest_release.outputs.data }}

  build-idf-rust:
    name: Build IDF Rust for ${{ matrix.os }}
    # needs: create_release
    needs: get_release
    runs-on: ${{ matrix.os }}
    env:
      working-directory: D:/
    strategy:
      matrix:
        os: [windows-latest]
        include:
        - os: windows-latest
          ARCH: ''
          TARGET: win-x64
          ASSET_PATH: 'build/dist/esp.zip'
          ASSET_NAME: 'rust-1.56.0.1-dev-x86_64-pc-windows-msvc.zip'
          ASSET_CONTENT_TYPE: 'application/zip'
          LLVM_ROOT_OPTION: ''
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: esp-rs/rust
          ref: esp-1.56.0
          submodules: true
      - name: Set up Python
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-18.04' || matrix.os == 'windows-latest' }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Setup Ninja
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-18.04' || matrix.os == 'windows-latest' }}
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Prepare build
        working-directory: D:/rust
        run: python3 src/bootstrap/configure.py ${{ matrix.LLVM_ROOT_OPTION }} --experimental-targets=Xtensa --enable-extended --tools=rustfmt --dist-compression-formats='xz'
      - name: Build with x.py - only components
        working-directory: D:/rust
        if: ${{ matrix.os == 'windows-self-hosted' ||  matrix.os == 'windows-latest' }}
        continue-on-error: true
        run: python3 x.py dist --stage 2
      - name: Build with x.py - dist packages
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-18.04' }}
        run: python3 x.py dist --stage 2
        # Excluding src/doc breaks build of 1.55
        #run: python3 x.py dist --stage 2 --exclude src/doc
      - name: Build with x.py - dist packages - with cached LLVM
        if: ${{ matrix.os == 'macos-m1-self-hosted' }}
        run: python3 x.py dist --stage 2 --exclude src/doc --llvm-skip-rebuild TRUE
      - name: Dist bundle for Windows
        working-directory: D:/rust/build/dist
        # Windows build has several issues:
        # - long path problem in version 1.56.0, build of some dist artifacts fails
        # - cp -r from stage2 is dangerous, because there is a src symlink to parent project dir which causes recursion
        # Following code is workaround which assembles minimal distribution of toolchain which should be extracted to ~/.rustup/toolchains.
        if: ${{ matrix.os == 'windows-self-hosted' || matrix.os == 'windows-latest' }}
        shell: pwsh
        run: |
          mkdir esp
          7z e rust-1.56.0-dev-x86_64-pc-windows-msvc.tar.xz
          7z x rust-1.56.0-dev-x86_64-pc-windows-msvc.tar
          pushd rust-1.56.0-dev-x86_64-pc-windows-msvc
          cp -Recurse .\rustc\bin ..\esp\
          cp -Recurse .\rustc\lib ..\esp\
          cp -Recurse .\rustc\share ..\esp\
          cp -ErrorAction SilentlyContinue -Recurse .\rust-std-x86_64-pc-windows-msvc\lib\* ..\esp\lib\
          popd
          7z e rust-src-1.56.0-dev.tar.xz
          7z x rust-src-1.56.0-dev.tar
          pushd rust-src-1.56.0-dev
          cp -ErrorAction SilentlyContinue -Recurse .\rust-src\lib\* ..\esp\lib\
          popd
          7z a esp.zip esp/
      - name: Upload Release Asset
        working-directory: D:/rust/build/dist
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.get_release.outputs.upload_url }}
          asset_path: ${{ matrix.ASSET_PATH }}
          asset_name: ${{ matrix.ASSET_NAME }}
          asset_content_type: ${{ matrix.ASSET_CONTENT_TYPE }}

