name: Upload installers to release

on:
  workflow_dispatch:
    inputs:
      rust_build_branch:
        description: 'Branch of rust-build to use'
        required: true
        default: 'main'
      release_version:
        description: 'Release Version for generation'
        required: true
        default: '1.57.0.2'
      rust_version:
        description: 'Version of esp rust to use'
        required: true
        default: '1.57.0'


# We Break this down into individual jobs to avoid disk space issues
jobs:

  upload-installers:
    name: Upload installation scripts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: "rust-build"
          ref: ${{ github.event.inputs.rust_build_branch }}
      - uses: ./rust-build/.github/actions/util/setup-envs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Bash installer
        id: upload-bash-installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.get_release.outputs.upload_url }}
          asset_path: Install-RustToolchain.ps1
          asset_name: Install-RustToolchain.ps1
          asset_content_type: text/plain
      - name: Upload PowerShell installer
        id: upload-powershell-installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.get_release.outputs.upload_url }}
          asset_path: Install-RustToolchain.ps1
          asset_name: Install-RustToolchain.ps1
          asset_content_type:  text/x-shellscript
