name: Test Linux x86_64 - build of Rust examples

on:
  workflow_dispatch:
    inputs:
      rust_build_branch:
        description: 'Branch with test scripts'
        required: true
        default: 'main'
      toolchain_version:
        description: 'Version of Rust IDF toolchain'
        required: true
        default: '1.56.0-dev'

jobs:
  build-idf-rust-examples:
    name: Build IDF Rust Examples for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        include:
        - os: ubuntu-20.04
          ARCH: ''
          TARGET: linux-x64
          ASSET_PATH: 'build/dist/rust-1.56.0-dev-x86_64-unknown-linux-gnu.tar.xz'
          ASSET_NAME: 'rust-1.56.0-dev-x86_64-unknown-linux-gnu.tar.xz'
          ASSET_CONTENT_TYPE: 'application/x-tar'
          LLVM_ROOT_OPTION: ''
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.rust_build_branch }}
      - name: Set up Python
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-20.04' || matrix.os == 'windows-latest' }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Setup Ninja
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-20.04' || matrix.os == 'windows-latest' }}
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Test Rust toolchain by compiling STD demo
        run: ./test-rust-toolchain.sh --toolchain-version ${{ github.event.inputs.toolchain_version }}

